baseURL = 'https://www.ablab.blog'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "stack"
googleAnalytics = 'G-Z2ER5PVVVK'

[params]

[params.article]
toc = true
readingTime = true

[params.article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0 no"
